version: "3.7"
services:
  clickhouse-server:
    image: yandex/clickhouse-server:19.17.5.18
    hostname: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_output:/clickhouse_output
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
